application: 8enmann
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: main.application

# https://developers.google.com/appengine/docs/python/config/appconfig#Static_File_Handlers
- url: /
  static_files: index.html
  upload: index.html

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  expiration: 7d

- url: /bower_components/(.*)
  static_files: bower_components/\1
  upload: bower_components/.*
  expiration: 7d

- url: /(.*\.(js|html|css|ico))
  static_files: \1
  upload: (.*\.(js|html|css|png|ico))



libraries:
# Needed for endpoints/users_id_token.py.
- name: pycrypto
  version: "2.6"
- name: endpoints
  version: "1.0"
